// imports WORD from library
%import common.DIGIT
%import common.INT
%import common.SIGNED_INT
%import common.SIGNED_FLOAT
%import common.ESCAPED_STRING
%import common.SH_COMMENT
%import common.WS

%ignore WS
%ignore SH_COMMENT


start: extern_declaration*
?extern_declaration: function




declarator: IDENTIFIER
        | 

// Base types
FUNCTION: "function"
VAR: "var"
RETURN: "return"
IDENTIFIER: ("_"|LETTER) ("_"|LETTER|DIGIT)*
SINT: SIGNED_INT
FLOAT: SIGNED_FLOAT
STRING: ESCAPED_STRING
